"""
This type stub file was generated by pyright.
"""

import pandas as pd
from abc import ABC, abstractmethod
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path
from typing import Any
from .signal import Signal, SignalBatch

"""
Base model classes and registry for SignalCore.

All models must be testable, reproducible, and auditable.
"""
@dataclass
class ModelConfig:
    """
    Configuration for a SignalCore model.

    Attributes:
        model_id: Unique identifier
        model_type: Type of model (technical, ml, factor, etc.)
        version: Version string
        parameters: Model-specific parameters
        enabled: Whether model is active
        min_data_points: Minimum data required
        lookback_period: Historical data window needed
        update_frequency: How often to generate signals
    """
    model_id: str
    model_type: str
    version: str = ...
    parameters: dict[str, Any] = ...
    enabled: bool = ...
    min_data_points: int = ...
    lookback_period: int = ...
    update_frequency: str = ...
    metadata: dict[str, Any] = ...


class Model(ABC):
    """
    Abstract base class for all SignalCore models.

    All models must implement:
    - generate(): Produce signals from market data
    - validate(): Check if model can generate valid signals
    - describe(): Provide model metadata and state

    Models are stateless processors - they don't maintain internal state
    beyond their configuration.
    """
    def __init__(self, config: ModelConfig) -> None:
        """
        Initialize model with configuration.

        Args:
            config: Model configuration
        """
        ...
    
    @abstractmethod
    async def generate(self, symbol: str, data: pd.DataFrame, timestamp: datetime) -> Signal:
        """
        Generate trading signal from market data.

        Args:
            symbol: Stock ticker symbol
            data: Historical OHLCV data (indexed by timestamp)
            timestamp: Current time for signal generation

        Returns:
            Signal object with model predictions

        Raises:
            ValueError: If data is insufficient or invalid
        """
        ...
    
    def validate(self, data: pd.DataFrame) -> tuple[bool, str]:
        """
        Validate if model can generate signals from ordinis.data.

        Args:
            data: Historical OHLCV data

        Returns:
            (is_valid, message) tuple
        """
        ...
    
    def describe(self) -> dict[str, Any]:
        """
        Get model metadata and current state.

        Returns:
            Dictionary with model information
        """
        ...
    
    def __repr__(self) -> str:
        """String representation."""
        ...
    
    def save(self, path: Path) -> None:
        """
        Save model to disk.

        Subclasses with trainable state (e.g., neural networks, scalers)
        MUST override this method to persist their artifacts.

        Args:
            path: Directory to save model artifacts.
        """
        ...
    
    @classmethod
    def load(cls, path: Path) -> Model:
        """
        Load model from disk.

        Subclasses with trainable state MUST override this method.

        Args:
            path: Directory containing model artifacts.

        Returns:
            Loaded model instance.
        """
        ...
    
    def get_artifact_path(self, base_dir: Path) -> Path:
        """
        Get the standard artifact path for this model.

        Args:
            base_dir: Base directory for model artifacts.

        Returns:
            Path: models/{model_id}/{version}/
        """
        ...
    


class ModelRegistry:
    """
    Registry for managing SignalCore models.

    Provides model registration, retrieval, and lifecycle management.
    """
    def __init__(self) -> None:
        """Initialize empty registry."""
        ...
    
    def register(self, model: Model) -> None:
        """
        Register a model in the registry.

        Args:
            model: Model instance to register

        Raises:
            ValueError: If model_id already registered
        """
        ...
    
    def unregister(self, model_id: str) -> None:
        """
        Remove model from registry.

        Args:
            model_id: Model identifier

        Raises:
            KeyError: If model not found
        """
        ...
    
    def get(self, model_id: str) -> Model:
        """
        Get model by ID.

        Args:
            model_id: Model identifier

        Returns:
            Model instance

        Raises:
            KeyError: If model not found
        """
        ...
    
    def list_models(self, enabled_only: bool = ...) -> list[str]:
        """
        List registered model IDs.

        Args:
            enabled_only: Only return enabled models

        Returns:
            List of model IDs
        """
        ...
    
    def get_by_type(self, model_type: str) -> list[Model]:
        """
        Get all models of a specific type.

        Args:
            model_type: Model type to filter

        Returns:
            List of matching models
        """
        ...
    
    async def generate_all(self, data: dict[str, pd.DataFrame], timestamp: datetime) -> SignalBatch:
        """
        Generate signals from all enabled models.

        Args:
            data: Dictionary of symbol -> OHLCV data
            timestamp: Current timestamp

        Returns:
            SignalBatch with signals from all models
        """
        ...
    
    def to_dict(self) -> dict[str, Any]:
        """Get registry state as dictionary."""
        ...
    
    def save_all(self, base_dir: Path) -> dict[str, Path]:
        """
        Save all registered models to disk.

        Args:
            base_dir: Base directory for model artifacts.

        Returns:
            Dictionary mapping model_id -> save path.
        """
        ...
    
    def load_all(self, base_dir: Path, model_classes: dict[str, type]) -> list[str]:
        """
        Load all models from disk.

        Args:
            base_dir: Base directory containing model artifacts.
            model_classes: Dictionary mapping class names to model classes.

        Returns:
            List of loaded model IDs.
        """
        ...
    


registry = ...
