"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from pydantic import BaseModel

"""
Market data domain models.
"""
class Bar(BaseModel):
    """
    OHLCV bar data for a single time period.
    """
    symbol: str
    timestamp: datetime
    open: float
    high: float
    low: float
    close: float
    volume: float
    vwap: float | None = ...
    trade_count: int | None = ...
    model_config = ...


