"""
This type stub file was generated by pyright.
"""

from datetime import datetime
from pydantic import BaseModel
from ordinis.domain.enums import PositionSide

"""
Position domain models.
"""
class Position(BaseModel):
    """
    Trading position for a symbol.
    Tracks current holdings, P&L, and position history.
    """
    symbol: str
    side: PositionSide = ...
    quantity: int = ...
    avg_entry_price: float = ...
    current_price: float = ...
    realized_pnl: float = ...
    unrealized_pnl: float = ...
    sector: str | None = ...
    entry_time: datetime | None = ...
    last_update_time: datetime = ...
    multiplier: float = ...
    initial_margin: float = ...
    maintenance_margin: float = ...
    expiry: datetime | None = ...
    @property
    def market_value(self) -> float:
        """Get current market value of position."""
        ...
    
    @property
    def cost_basis(self) -> float:
        """Get total cost basis."""
        ...
    
    @property
    def total_pnl(self) -> float:
        """Get total P&L (realized + unrealized)."""
        ...
    
    @property
    def pnl_pct(self) -> float:
        """Get P&L as percentage of cost basis."""
        ...
    
    @property
    def is_open(self) -> bool:
        """Check if position is open."""
        ...
    
    def is_flat(self) -> bool:
        """Check if position is flat (no holdings)."""
        ...
    
    def update_price(self, price: float, timestamp: datetime): # -> None:
        """Update current price and unrealized P&L."""
        ...
    


class Trade(BaseModel):
    """
    Completed trade with entry and exit.
    """
    trade_id: str = ...
    symbol: str
    side: PositionSide
    entry_time: datetime
    exit_time: datetime
    entry_price: float
    exit_price: float
    quantity: int
    pnl: float
    pnl_pct: float
    commission: float
    duration: float
    @property
    def is_winner(self) -> bool:
        """Check if trade was profitable."""
        ...
    
    @property
    def is_loser(self) -> bool:
        """Check if trade was a loss."""
        ...
    


