"""
This type stub file was generated by pyright.
"""

import pandas as pd

"""
Technical indicator calculations for feature engineering.

All indicators are based on standard financial formulas.

NOTE: This module delegates core calculations to ordinis.quant.gs_quant_adapter
for consistency across the codebase. The wrapper methods here maintain backwards
compatibility with existing call sites.

TODO(refactor): Consider deprecating this class in favor of direct ordinis.quant imports.
See docs/gs_quant_integration_analysis.md for consolidation recommendations.
"""
class TechnicalIndicators:
    """
    Technical indicator calculations.

    NOTE: Core indicator functions (RSI, Bollinger Bands, MACD, etc.) now delegate
    to ordinis.quant for canonical implementations. This class provides backwards-
    compatible wrappers that preserve the original API signatures.
    """
    @staticmethod
    def sma(data: pd.Series, window: int) -> pd.Series:
        """
        Simple Moving Average.

        Args:
            data: Price series
            window: Number of periods

        Returns:
            SMA series
        """
        ...
    
    @staticmethod
    def ema(data: pd.Series, span: int) -> pd.Series:
        """
        Exponential Moving Average.

        Args:
            data: Price series
            span: Number of periods

        Returns:
            EMA series
        """
        ...
    
    @staticmethod
    def rsi(data: pd.Series, window: int = ...) -> pd.Series:
        """
        Relative Strength Index.

        Args:
            data: Price series
            window: Number of periods (default 14)

        Returns:
            RSI series (0-100)
        """
        ...
    
    @staticmethod
    def bollinger_bands(data: pd.Series, window: int = ..., num_std: float = ...) -> tuple[pd.Series, pd.Series, pd.Series]:
        """
        Bollinger Bands.

        Args:
            data: Price series
            window: Number of periods
            num_std: Number of standard deviations

        Returns:
            (middle_band, upper_band, lower_band) tuple
        """
        ...
    
    @staticmethod
    def macd(data: pd.Series, fast: int = ..., slow: int = ..., signal: int = ...) -> tuple[pd.Series, pd.Series, pd.Series]:
        """
        Moving Average Convergence Divergence.

        Args:
            data: Price series
            fast: Fast EMA period
            slow: Slow EMA period
            signal: Signal line period

        Returns:
            (macd, signal, histogram) tuple
        """
        ...
    
    @staticmethod
    def atr(high: pd.Series, low: pd.Series, close: pd.Series, window: int = ...) -> pd.Series:
        """
        Average True Range.

        Args:
            high: High prices
            low: Low prices
            close: Close prices
            window: Number of periods

        Returns:
            ATR series
        """
        ...
    
    @staticmethod
    def z_score(data: pd.Series, window: int = ...) -> pd.Series:
        """
        Rolling Z-Score.

        (Value - Mean) / StdDev

        Args:
            data: Price series
            window: Rolling window size

        Returns:
            Z-Score series
        """
        ...
    
    @staticmethod
    def stochastic(high: pd.Series, low: pd.Series, close: pd.Series, window: int = ...) -> tuple[pd.Series, pd.Series]:
        """
        Stochastic Oscillator.

        Args:
            high: High prices
            low: Low prices
            close: Close prices
            window: Number of periods

        Returns:
            (%K, %D) tuple
        """
        ...
    
    @staticmethod
    def adx(high: pd.Series, low: pd.Series, close: pd.Series, window: int = ...) -> pd.Series:
        """
        Average Directional Index.

        Args:
            high: High prices
            low: Low prices
            close: Close prices
            window: Number of periods

        Returns:
            ADX series
        """
        ...
    
    @staticmethod
    def obv(close: pd.Series, volume: pd.Series) -> pd.Series:
        """
        On-Balance Volume.

        Args:
            close: Close prices
            volume: Volume

        Returns:
            OBV series
        """
        ...
    
    @staticmethod
    def vwap(high: pd.Series, low: pd.Series, close: pd.Series, volume: pd.Series, window: int | None = ...) -> pd.Series:
        """
        Volume-Weighted Average Price.

        Args:
            high: High prices
            low: Low prices
            close: Close prices
            volume: Volume
            window: Rolling window size (optional). If None, calculates cumulative VWAP.

        Returns:
            VWAP series
        """
        ...
    


