"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator
from ordinis.ai.helix.models import ChatMessage, ChatResponse, EmbeddingResponse, ModelInfo, ProviderType
from ordinis.ai.helix.providers.base import BaseProvider

"""
Mistral AI provider implementation.

Integrates with Mistral AI API for code generation and chat.
"""
_logger = ...
class MistralProvider(BaseProvider):
    """Mistral AI API provider."""
    def __init__(self, api_key: str | None = ...) -> None:
        """
        Initialize Mistral provider.

        Args:
            api_key: Mistral API key. If None, uses MISTRAL_API_KEY env var.
        """
        ...
    
    @property
    def provider_type(self) -> ProviderType:
        """Return provider type."""
        ...
    
    @property
    def is_available(self) -> bool:
        """Check if Mistral API is available."""
        ...
    
    async def chat(self, messages: list[ChatMessage], model: ModelInfo, temperature: float | None = ..., max_tokens: int | None = ..., stop: list[str] | None = ..., **kwargs: object) -> ChatResponse:
        """Generate chat completion via Mistral API."""
        ...
    
    async def chat_stream(self, messages: list[ChatMessage], model: ModelInfo, temperature: float | None = ..., max_tokens: int | None = ..., **kwargs: object) -> AsyncIterator[str]:
        """Generate streaming chat completion."""
        ...
    
    async def embed(self, texts: list[str], model: ModelInfo, **kwargs: object) -> EmbeddingResponse:
        """Generate embeddings via Mistral API."""
        ...
    
    async def health_check(self) -> bool:
        """Verify Mistral API connectivity."""
        ...
    


