"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator
from ordinis.ai.helix.models import ChatMessage, ChatResponse, EmbeddingResponse, ModelInfo, ProviderType
from ordinis.ai.helix.providers.base import BaseProvider

"""
NVIDIA API provider implementation.

Integrates with NVIDIA AI Endpoints for LLM inference.
"""
_logger = ...
class NVIDIAProvider(BaseProvider):
    """NVIDIA AI Endpoints provider."""
    def __init__(self, api_key: str | None = ...) -> None:
        """
        Initialize NVIDIA provider.

        Args:
            api_key: NVIDIA API key. If None, uses NVIDIA_API_KEY env var.
        """
        ...
    
    @property
    def provider_type(self) -> ProviderType:
        """Return provider type."""
        ...
    
    @property
    def is_available(self) -> bool:
        """Check if NVIDIA API is available."""
        ...
    
    async def chat(self, messages: list[ChatMessage], model: ModelInfo, temperature: float | None = ..., max_tokens: int | None = ..., stop: list[str] | None = ..., **kwargs: object) -> ChatResponse:
        """Generate chat completion via NVIDIA API."""
        ...
    
    async def chat_stream(self, messages: list[ChatMessage], model: ModelInfo, temperature: float | None = ..., max_tokens: int | None = ..., **kwargs: object) -> AsyncIterator[str]:
        """Generate streaming chat completion."""
        ...
    
    async def embed(self, texts: list[str], model: ModelInfo, **kwargs: object) -> EmbeddingResponse:
        """Generate embeddings via NVIDIA API."""
        ...
    
    async def health_check(self) -> bool:
        """Verify NVIDIA API connectivity."""
        ...
    


