"""
This type stub file was generated by pyright.
"""

from collections.abc import AsyncIterator
from ordinis.ai.helix.models import ChatMessage, ChatResponse, EmbeddingResponse, ModelInfo, ProviderType
from ordinis.ai.helix.providers.base import BaseProvider

"""
OpenAI provider implementation.

Integrates with OpenAI API for chat and embeddings.
"""
_logger = ...
class OpenAIProvider(BaseProvider):
    """OpenAI API provider."""
    def __init__(self, api_key: str | None = ..., organization: str | None = ...) -> None:
        """
        Initialize OpenAI provider.

        Args:
            api_key: OpenAI API key. If None, uses OPENAI_API_KEY env var.
            organization: OpenAI organization ID (optional).
        """
        ...
    
    @property
    def provider_type(self) -> ProviderType:
        """Return provider type."""
        ...
    
    @property
    def is_available(self) -> bool:
        """Check if OpenAI API is available."""
        ...
    
    async def chat(self, messages: list[ChatMessage], model: ModelInfo, temperature: float | None = ..., max_tokens: int | None = ..., stop: list[str] | None = ..., **kwargs: object) -> ChatResponse:
        """Generate chat completion via OpenAI API."""
        ...
    
    async def chat_stream(self, messages: list[ChatMessage], model: ModelInfo, temperature: float | None = ..., max_tokens: int | None = ..., **kwargs: object) -> AsyncIterator[str]:
        """Generate streaming chat completion."""
        ...
    
    async def embed(self, texts: list[str], model: ModelInfo, **kwargs: object) -> EmbeddingResponse:
        """Generate embeddings via OpenAI API."""
        ...
    
    async def health_check(self) -> bool:
        """Verify OpenAI API connectivity."""
        ...
    


