"""
This type stub file was generated by pyright.
"""

from ordinis.engines.base.config import AIEngineConfig, BaseEngineConfig, DataEngineConfig, TradingEngineConfig
from ordinis.engines.base.engine import BaseEngine
from ordinis.engines.base.hooks import BaseGovernanceHook, CompositeGovernanceHook, Decision, GovernanceHook, PreflightContext, PreflightResult
from ordinis.engines.base.models import AuditRecord, EngineError, EngineMetrics, EngineState, HealthLevel, HealthStatus
from ordinis.engines.base.requirements import Requirement, RequirementCategory, RequirementPriority, RequirementRegistry, RequirementStatus, RequirementVerification, verifies

"""Base engine framework for Ordinis.

This module provides the foundational classes and protocols that all
Ordinis engines must implement for consistent lifecycle management,
governance, and observability.

Standard Engine Template:
    engines/{engine_name}/
    ├── __init__.py              # Public API exports
    ├── core/
    │   ├── __init__.py
    │   ├── engine.py            # Main engine class (extends BaseEngine)
    │   ├── config.py            # Engine config (extends BaseEngineConfig)
    │   └── models.py            # Data models/schemas
    ├── hooks/
    │   ├── __init__.py
    │   └── governance.py        # Engine-specific governance
    └── {domain_specific}/       # Engine-specific folders

Example:
    from ordinis.engines.base import BaseEngine, BaseEngineConfig, HealthStatus

    class MyEngineConfig(BaseEngineConfig):
        custom_setting: str = "default"

    class MyEngine(BaseEngine[MyEngineConfig]):
        async def _do_initialize(self) -> None:
            # Setup resources
            pass

        async def _do_shutdown(self) -> None:
            # Cleanup
            pass

        async def _do_health_check(self) -> HealthStatus:
            return HealthStatus(level=HealthLevel.HEALTHY, message="OK")
"""
__all__ = ["AIEngineConfig", "AuditRecord", "BaseEngine", "BaseEngineConfig", "BaseGovernanceHook", "CompositeGovernanceHook", "DataEngineConfig", "Decision", "EngineError", "EngineMetrics", "EngineState", "GovernanceHook", "HealthLevel", "HealthStatus", "PreflightContext", "PreflightResult", "Requirement", "RequirementCategory", "RequirementPriority", "RequirementRegistry", "RequirementStatus", "RequirementVerification", "TradingEngineConfig", "verifies"]
