"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from pathlib import Path
from typing import Any

"""Base configuration for all Ordinis engines.

This module defines the standard configuration structure that
all engines must implement for consistent configuration management.
"""
@dataclass
class BaseEngineConfig:
    """Base configuration shared by all engines.

    All engine-specific configs should inherit from this class
    to ensure consistent configuration patterns.

    Attributes:
        enabled: Whether the engine is enabled.
        name: Engine instance name (for logging/metrics).
        log_level: Logging level (DEBUG, INFO, WARNING, ERROR).
        metrics_enabled: Enable metrics collection.
        health_check_interval_seconds: Interval between health checks.
        timeout_seconds: Default operation timeout.
        retry_attempts: Number of retry attempts for recoverable errors.
        retry_delay_seconds: Delay between retries.
        governance_enabled: Enable governance hooks.
        audit_enabled: Enable audit logging.
    """
    enabled: bool = ...
    name: str = ...
    log_level: str = ...
    metrics_enabled: bool = ...
    health_check_interval_seconds: float = ...
    timeout_seconds: float = ...
    retry_attempts: int = ...
    retry_delay_seconds: float = ...
    governance_enabled: bool = ...
    audit_enabled: bool = ...
    def __post_init__(self) -> None:
        """Validate configuration after initialization."""
        ...
    
    def validate(self) -> list[str]:
        """Validate configuration parameters.

        Returns:
            List of validation error messages (empty if valid).
        """
        ...
    
    def to_dict(self) -> dict[str, Any]:
        """Convert config to dictionary for serialization."""
        ...
    


@dataclass
class AIEngineConfig(BaseEngineConfig):
    """Configuration for AI-enabled engines.

    Extends base config with AI/LLM-specific settings.

    Attributes:
        model_name: Default model to use.
        fallback_model: Fallback model if primary unavailable.
        max_tokens: Maximum tokens for generation.
        temperature: Model temperature (0.0-1.0).
        api_timeout_seconds: API call timeout.
        cache_enabled: Enable response caching.
        cache_ttl_seconds: Cache time-to-live.
    """
    model_name: str = ...
    fallback_model: str = ...
    max_tokens: int = ...
    temperature: float = ...
    api_timeout_seconds: float = ...
    cache_enabled: bool = ...
    cache_ttl_seconds: int = ...


@dataclass
class DataEngineConfig(BaseEngineConfig):
    """Configuration for data-processing engines.

    Extends base config with data-specific settings.

    Attributes:
        batch_size: Default batch size for processing.
        buffer_size: Internal buffer size.
        checkpoint_enabled: Enable checkpointing.
        checkpoint_path: Path for checkpoint files.
        parallel_workers: Number of parallel workers.
    """
    batch_size: int = ...
    buffer_size: int = ...
    checkpoint_enabled: bool = ...
    checkpoint_path: Path = ...
    parallel_workers: int = ...


@dataclass
class TradingEngineConfig(BaseEngineConfig):
    """Configuration for trading-related engines.

    Extends base config with trading-specific settings.

    Attributes:
        paper_mode: Run in paper trading mode.
        max_position_size: Maximum position size.
        daily_loss_limit: Daily loss limit in dollars.
        max_drawdown_pct: Maximum drawdown percentage.
        symbols: List of symbols to trade.
    """
    paper_mode: bool = ...
    max_position_size: float = ...
    daily_loss_limit: float = ...
    max_drawdown_pct: float = ...
    symbols: list[str] = ...


