"""
This type stub file was generated by pyright.
"""

from abc import ABC
from collections.abc import AsyncIterator
from contextlib import asynccontextmanager
from typing import Any, Generic, TypeVar
from ordinis.engines.base.config import BaseEngineConfig
from ordinis.engines.base.hooks import GovernanceHook, PreflightResult
from ordinis.engines.base.models import EngineMetrics, EngineState, HealthStatus
from ordinis.engines.base.requirements import RequirementRegistry

"""Base engine protocol and abstract class.

This module defines the standard interface that all Ordinis engines
must implement for consistent lifecycle management, health monitoring,
and governance integration.
"""
ConfigT = TypeVar("ConfigT", bound=BaseEngineConfig)
_tracer = ...
class BaseEngine(ABC, Generic[ConfigT]):
    """Abstract base class for all Ordinis engines.

    Provides standard lifecycle management, health monitoring,
    metrics collection, and governance integration.

    All engines must inherit from this class and implement
    the abstract methods.

    Type Parameters:
        ConfigT: The configuration type for this engine.

    Attributes:
        config: Engine configuration.
        state: Current engine state.
        requirements: Requirement registry for this engine.
    """
    def __init__(self, config: ConfigT, governance_hook: GovernanceHook | None = ...) -> None:
        """Initialize the engine.

        Args:
            config: Engine configuration.
            governance_hook: Optional governance hook (uses default if None).
        """
        ...
    
    @property
    def name(self) -> str:
        """Engine name for logging and metrics."""
        ...
    
    @property
    def config(self) -> ConfigT:
        """Engine configuration."""
        ...
    
    @property
    def state(self) -> EngineState:
        """Current engine state."""
        ...
    
    @property
    def is_running(self) -> bool:
        """Check if engine is operational."""
        ...
    
    @property
    def requirements(self) -> RequirementRegistry:
        """Requirement registry for this engine."""
        ...
    
    @property
    def governance(self) -> GovernanceHook:
        """Governance hook for this engine."""
        ...
    
    async def initialize(self) -> None:
        """Initialize the engine.

        Sets up resources and transitions to READY state.

        Raises:
            RuntimeError: If engine is already initialized.
            Exception: If initialization fails.
        """
        ...
    
    async def shutdown(self) -> None:
        """Shutdown the engine.

        Cleans up resources and transitions to STOPPED state.
        """
        ...
    
    async def health_check(self) -> HealthStatus:
        """Check engine health.

        Returns:
            HealthStatus with current health information.
        """
        ...
    
    def get_metrics(self) -> EngineMetrics:
        """Get current engine metrics.

        Returns:
            EngineMetrics with performance statistics.
        """
        ...
    
    async def preflight(self, action: str, inputs: dict[str, Any] | None = ..., **metadata: Any) -> PreflightResult:
        """Run governance preflight check.

        Args:
            action: The action being attempted.
            inputs: Operation inputs (sanitized).
            **metadata: Additional context.

        Returns:
            PreflightResult with decision.
        """
        ...
    
    async def audit(self, action: str, inputs: dict[str, Any] | None = ..., outputs: dict[str, Any] | None = ..., model_used: str | None = ..., latency_ms: float | None = ..., **metadata: Any) -> None:
        """Record an audit event.

        Args:
            action: The action performed.
            inputs: Operation inputs (sanitized).
            outputs: Operation outputs (sanitized).
            model_used: AI model used (if applicable).
            latency_ms: Operation latency.
            **metadata: Additional context.
        """
        ...
    
    @asynccontextmanager
    async def track_operation(self, action: str, inputs: dict[str, Any] | None = ...) -> AsyncIterator[dict[str, Any]]:
        """Context manager for tracking operations with OpenTelemetry tracing.

        Handles preflight, metrics, audit, and distributed tracing automatically.

        Args:
            action: The action being performed.
            inputs: Operation inputs.

        Yields:
            Context dict for storing outputs.

        Raises:
            PermissionError: If preflight denies the operation.

        Example:
            async with self.track_operation("generate_signal", {"symbol": "AAPL"}) as ctx:
                result = await self._generate_signal("AAPL")
                ctx["outputs"] = {"signal": result}
        """
        ...
    
    def __repr__(self) -> str:
        """String representation of the engine."""
        ...
    


