"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any, Protocol
from ordinis.engines.base.models import AuditRecord, EngineError

"""Governance hooks for engine operations.

This module defines the standard hook interfaces that all engines
must implement for consistent governance, audit, and policy enforcement.

Hooks are called at engine boundaries:
- preflight(): Before an operation (can block)
- audit(): After an operation (records outcome)
- on_error(): When an error occurs
"""
_logger = ...
class Decision(Enum):
    """Governance decision outcomes."""
    ALLOW = ...
    DENY = ...
    WARN = ...
    DEFER = ...


@dataclass
class PreflightContext:
    """Context passed to preflight checks.

    Attributes:
        engine: Engine name.
        action: Operation being attempted.
        inputs: Operation inputs (sanitized).
        trace_id: Distributed trace ID.
        user_id: User initiating the action (if applicable).
        metadata: Additional context.
    """
    engine: str
    action: str
    inputs: dict[str, Any] = ...
    trace_id: str | None = ...
    user_id: str | None = ...
    metadata: dict[str, Any] = ...
    @property
    def parameters(self) -> dict[str, Any]:
        """Alias for inputs (backward compatibility)."""
        ...
    
    @property
    def operation(self) -> str:
        """Alias for action (backward compatibility)."""
        ...
    
    @property
    def timestamp(self) -> Any:
        """Get timestamp from metadata."""
        ...
    


@dataclass
class PreflightResult:
    """Result from a preflight check.

    Attributes:
        decision: Allow/deny/warn/defer.
        reason: Explanation for the decision.
        policy_id: ID of the policy that made the decision.
        policy_version: Version of the policy.
        adjustments: Suggested modifications to inputs.
        warnings: List of warnings to log.
        expires_at: When this decision expires (for caching).
    """
    decision: Decision
    reason: str = ...
    policy_id: str | None = ...
    policy_version: str | None = ...
    adjustments: dict[str, Any] = ...
    warnings: list[str] = ...
    expires_at: datetime | None = ...
    @property
    def allowed(self) -> bool:
        """Check if operation is allowed to proceed."""
        ...
    
    @property
    def blocked(self) -> bool:
        """Check if operation is blocked."""
        ...
    


class GovernanceHook(Protocol):
    """Protocol for governance hooks.

    All engines must implement this protocol to enable
    consistent governance across the system.
    """
    async def preflight(self, context: PreflightContext) -> PreflightResult:
        """Check if an operation should proceed.

        Called before every significant engine operation.
        Can block operations that violate policies.

        Args:
            context: Operation context including inputs.

        Returns:
            PreflightResult with decision and metadata.
        """
        ...
    
    async def audit(self, record: AuditRecord) -> None:
        """Record an audit event.

        Called after every significant engine operation.
        Should never block or raise exceptions.

        Args:
            record: Audit record to persist.
        """
        ...
    
    async def on_error(self, error: EngineError) -> None:
        """Handle an engine error.

        Called when an error occurs during operation.
        Used for alerting and error tracking.

        Args:
            error: Structured error information.
        """
        ...
    


class BaseGovernanceHook:
    """Base class for governance hooks.

    Provides default implementations that can be overridden.
    Engines should extend this class for their hooks.
    """
    def __init__(self, engine_name: str) -> None:
        """Initialize the governance hook.

        Args:
            engine_name: Name of the engine using this hook.
        """
        ...
    
    @property
    def policy_version(self) -> str:
        """Get the current policy version."""
        ...
    
    async def preflight(self, context: PreflightContext) -> PreflightResult:
        """Default preflight: allow all operations.

        Override this method to implement custom policies.

        Args:
            context: Operation context.

        Returns:
            PreflightResult allowing the operation.
        """
        ...
    
    async def audit(self, record: AuditRecord) -> None:
        """Default audit: log to standard logger.

        Override this method to persist to database, send to
        external audit system, etc.

        Args:
            record: Audit record to persist.
        """
        ...
    
    async def on_error(self, error: EngineError) -> None:
        """Default error handler: log the error.

        Override this method to send alerts, update dashboards, etc.

        Args:
            error: Structured error information.
        """
        ...
    


class CompositeGovernanceHook(BaseGovernanceHook):
    """Combines multiple governance hooks.

    Executes all hooks in order. For preflight, returns the most
    restrictive decision. For audit/error, calls all hooks.
    """
    def __init__(self, engine_name: str, hooks: list[GovernanceHook]) -> None:
        """Initialize with a list of hooks.

        Args:
            engine_name: Name of the engine.
            hooks: List of hooks to compose.
        """
        ...
    
    async def preflight(self, context: PreflightContext) -> PreflightResult:
        """Execute all preflight hooks, return most restrictive.

        Priority: DENY > DEFER > WARN > ALLOW

        Args:
            context: Operation context.

        Returns:
            Most restrictive PreflightResult from all hooks.
        """
        ...
    
    async def audit(self, record: AuditRecord) -> None:
        """Execute all audit hooks.

        Args:
            record: Audit record to persist.
        """
        ...
    
    async def on_error(self, error: EngineError) -> None:
        """Execute all error hooks.

        Args:
            error: Structured error information.
        """
        ...
    


