"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any

"""Common data models for all Ordinis engines.

This module defines shared data structures used across all engines
for consistent status reporting, error handling, and audit trails.
"""
class EngineState(Enum):
    """Lifecycle states for engines."""
    UNINITIALIZED = ...
    INITIALIZING = ...
    READY = ...
    RUNNING = ...
    PAUSED = ...
    STOPPING = ...
    STOPPED = ...
    ERROR = ...


class HealthLevel(Enum):
    """Health status levels."""
    HEALTHY = ...
    DEGRADED = ...
    UNHEALTHY = ...
    UNKNOWN = ...


@dataclass(frozen=True)
class HealthStatus:
    """Engine health status report.

    Attributes:
        level: Overall health level.
        message: Human-readable status message.
        details: Additional diagnostic information.
        last_check: Timestamp of health check.
        latency_ms: Response latency in milliseconds.
    """
    level: HealthLevel
    message: str
    details: dict[str, Any] = ...
    last_check: datetime = ...
    latency_ms: float | None = ...
    @property
    def is_healthy(self) -> bool:
        """Check if engine is operational."""
        ...
    


@dataclass(frozen=True)
class EngineMetrics:
    """Runtime metrics for an engine.

    Attributes:
        requests_total: Total requests processed.
        requests_failed: Failed request count.
        latency_p50_ms: Median latency.
        latency_p95_ms: 95th percentile latency.
        latency_p99_ms: 99th percentile latency.
        uptime_seconds: Time since initialization.
    """
    requests_total: int = ...
    requests_failed: int = ...
    latency_p50_ms: float = ...
    latency_p95_ms: float = ...
    latency_p99_ms: float = ...
    uptime_seconds: float = ...
    @property
    def error_rate(self) -> float:
        """Calculate error rate as percentage."""
        ...
    


@dataclass(frozen=True)
class AuditRecord:
    """Standardized audit record for governance tracking.

    Every engine operation should emit an audit record for
    compliance and debugging purposes.

    Attributes:
        engine: Engine name.
        action: Operation performed.
        timestamp: When the action occurred.
        trace_id: Distributed trace identifier.
        inputs: Sanitized input summary.
        outputs: Sanitized output summary.
        model_used: AI model used (if applicable).
        policy_version: Governance policy version applied.
        decision: Allow/deny/warn decision.
        latency_ms: Operation latency.
        metadata: Additional context.
    """
    engine: str
    action: str
    timestamp: datetime = ...
    trace_id: str | None = ...
    inputs: dict[str, Any] = ...
    outputs: dict[str, Any] = ...
    model_used: str | None = ...
    policy_version: str | None = ...
    decision: str | None = ...
    latency_ms: float | None = ...
    metadata: dict[str, Any] = ...


@dataclass
class EngineError:
    """Structured error information.

    Attributes:
        code: Error code for programmatic handling.
        message: Human-readable error message.
        engine: Engine that raised the error.
        recoverable: Whether the error is recoverable.
        details: Additional error context.
        timestamp: When the error occurred.
    """
    code: str
    message: str
    engine: str
    recoverable: bool = ...
    details: dict[str, Any] = ...
    timestamp: datetime = ...


