"""
This type stub file was generated by pyright.
"""

from collections.abc import Callable
from dataclasses import dataclass
from datetime import datetime
from enum import Enum
from typing import Any

"""Engine requirements framework for traceable, verifiable, testable specifications.

This module provides a structured way to define, track, and verify
engine requirements with unique IDs for audit and compliance.

Requirements follow the pattern: {ENGINE}-{CATEGORY}-{NUMBER}
Example: SIGNAL-FUNC-001, RISK-PERF-003, EXEC-SEC-002

Categories:
- FUNC: Functional requirements (what it does)
- PERF: Performance requirements (how fast/efficient)
- SEC: Security requirements (access, data protection)
- REL: Reliability requirements (uptime, recovery)
- GOV: Governance requirements (audit, compliance)
- INT: Integration requirements (interfaces, dependencies)
"""
class RequirementCategory(Enum):
    """Requirement categories for classification."""
    FUNC = ...
    PERF = ...
    SEC = ...
    REL = ...
    GOV = ...
    INT = ...


class RequirementPriority(Enum):
    """Requirement priority levels."""
    CRITICAL = ...
    HIGH = ...
    MEDIUM = ...
    LOW = ...


class RequirementStatus(Enum):
    """Requirement implementation status."""
    DRAFT = ...
    APPROVED = ...
    IN_PROGRESS = ...
    IMPLEMENTED = ...
    VERIFIED = ...
    DEFERRED = ...
    REJECTED = ...


@dataclass
class Requirement:
    """A traceable, verifiable requirement specification.

    Attributes:
        id: Unique requirement ID (e.g., SIGNAL-FUNC-001).
        title: Short descriptive title.
        description: Detailed requirement description.
        category: Requirement category.
        priority: Priority level.
        status: Implementation status.
        acceptance_criteria: List of testable acceptance criteria.
        test_ids: Associated test case IDs.
        dependencies: IDs of dependent requirements.
        version: Requirement version.
        created_at: Creation timestamp.
        updated_at: Last update timestamp.
        created_by: Author identifier.
        rationale: Why this requirement exists.
        references: External references (docs, tickets, etc.).
    """
    id: str
    title: str
    description: str
    category: RequirementCategory
    priority: RequirementPriority = ...
    status: RequirementStatus = ...
    acceptance_criteria: list[str] = ...
    test_ids: list[str] = ...
    dependencies: list[str] = ...
    version: str = ...
    created_at: datetime = ...
    updated_at: datetime = ...
    created_by: str = ...
    rationale: str = ...
    references: list[str] = ...
    def __post_init__(self) -> None:
        """Validate requirement ID format."""
        ...
    
    @property
    def engine(self) -> str:
        """Extract engine name from ID."""
        ...
    
    @property
    def is_testable(self) -> bool:
        """Check if requirement has associated tests."""
        ...
    
    @property
    def is_verified(self) -> bool:
        """Check if requirement is verified."""
        ...
    


@dataclass
class RequirementVerification:
    """Verification result for a requirement.

    Attributes:
        requirement_id: ID of the verified requirement.
        passed: Whether verification passed.
        test_results: Results from each test.
        verified_at: Verification timestamp.
        verified_by: Verifier identifier (human or CI).
        evidence: Supporting evidence (logs, screenshots, etc.).
        notes: Additional verification notes.
    """
    requirement_id: str
    passed: bool
    test_results: dict[str, bool] = ...
    verified_at: datetime = ...
    verified_by: str = ...
    evidence: list[str] = ...
    notes: str = ...
    @property
    def coverage(self) -> float:
        """Calculate test coverage percentage."""
        ...
    


class RequirementRegistry:
    """Registry for managing engine requirements.

    Provides centralized storage and querying of requirements
    with verification tracking.
    """
    def __init__(self, engine_name: str) -> None:
        """Initialize registry for an engine.

        Args:
            engine_name: Name of the engine (e.g., SIGNAL, RISK).
        """
        ...
    
    def register(self, requirement: Requirement) -> None:
        """Register a requirement.

        Args:
            requirement: The requirement to register.

        Raises:
            ValueError: If requirement ID already exists or wrong engine.
        """
        ...
    
    def create(self, category: RequirementCategory, title: str, description: str, **kwargs: Any) -> Requirement:
        """Create and register a new requirement with auto-generated ID.

        Args:
            category: Requirement category.
            title: Short title.
            description: Detailed description.
            **kwargs: Additional requirement attributes.

        Returns:
            The created and registered requirement.
        """
        ...
    
    def get(self, req_id: str) -> Requirement | None:
        """Get a requirement by ID."""
        ...
    
    def list_by_category(self, category: RequirementCategory) -> list[Requirement]:
        """List requirements by category."""
        ...
    
    def list_by_status(self, status: RequirementStatus) -> list[Requirement]:
        """List requirements by status."""
        ...
    
    def list_by_priority(self, priority: RequirementPriority) -> list[Requirement]:
        """List requirements by priority."""
        ...
    
    def record_verification(self, verification: RequirementVerification) -> None:
        """Record a verification result.

        Args:
            verification: The verification result to record.
        """
        ...
    
    def get_verifications(self, req_id: str) -> list[RequirementVerification]:
        """Get all verifications for a requirement."""
        ...
    
    def get_latest_verification(self, req_id: str) -> RequirementVerification | None:
        """Get the most recent verification for a requirement."""
        ...
    
    def compliance_report(self) -> dict[str, Any]:
        """Generate a compliance report for all requirements.

        Returns:
            Dictionary with compliance statistics and details.
        """
        ...
    
    def to_dict(self) -> dict[str, Any]:
        """Export all requirements to dictionary."""
        ...
    


def verifies(*requirement_ids: str) -> Callable:
    """Decorator to link a test function to requirements.

    Usage:
        @verifies("SIGNAL-FUNC-001", "SIGNAL-FUNC-002")
        def test_signal_generation():
            ...

    Args:
        *requirement_ids: Requirement IDs that this test verifies.

    Returns:
        Decorated function with requirement metadata.
    """
    ...

