"""
This type stub file was generated by pyright.
"""

from .gs_quant_adapter import AnnualizationFactor, Returns, Window, beta, bollinger_bands, correlation, exponential_moving_average, generate_series, macd, max_drawdown, moving_average, percentiles, prices, returns, rolling_max, rolling_mean, rolling_min, rolling_std, rsi, sharpe_ratio, volatility, zscores
from .qpo_adapter import DEFAULT_QPO_SRC, QPOEnvironmentError, QPOPortfolioOptimizer, QPOScenarioGenerator

"""
Quant integrations for Ordinis.

Includes adapters for:
- NVIDIA blueprint integrations (Quantitative Portfolio Optimization)
- Goldman Sachs gs-quant timeseries analytics (standalone, no API required)
"""
__all__ = ["DEFAULT_QPO_SRC", "QPOEnvironmentError", "QPOPortfolioOptimizer", "QPOScenarioGenerator", "Returns", "Window", "AnnualizationFactor", "returns", "prices", "moving_average", "exponential_moving_average", "bollinger_bands", "rsi", "macd", "volatility", "sharpe_ratio", "max_drawdown", "correlation", "beta", "zscores", "percentiles", "rolling_std", "rolling_mean", "rolling_min", "rolling_max", "generate_series"]
