"""
This type stub file was generated by pyright.
"""

import pandas as pd
from dataclasses import dataclass
from pathlib import Path
from typing import Any

"""
Adapters for the NVIDIA Quantitative Portfolio Optimization (QPO) blueprint.

These helpers keep the blueprint as an optional dependency and provide
guardrails so the rest of Ordinis can call into QPO when the GPU stack is
available, while failing gracefully when it is not.
"""
REPO_ROOT = ...
DEFAULT_QPO_SRC = ...
class QPOEnvironmentError(RuntimeError):
    """Raised when the QPO blueprint or its dependencies are unavailable."""
    ...


@dataclass
class QPOScenarioGenerator:
    """Wrapper around QPO scenario generation utilities."""
    qpo_src: Path = ...
    def generate(self, fitting_data: pd.DataFrame, generation_dates: list[pd.Timestamp] | Any, n_paths: int, method: str = ..., plot_paths: bool = ..., n_plots: int = ...) -> Any:
        """Generate synthetic forward paths using QPO's ForwardPathSimulator."""
        ...
    


@dataclass
class QPOPortfolioOptimizer:
    """Wrapper around QPO CVaR optimizer (cuOpt/CVXPY)."""
    qpo_src: Path = ...
    def optimize_from_returns(self, returns: pd.DataFrame, target_return: float = ..., max_weight: float = ..., risk_aversion: float = ..., api: str = ..., solver_settings: dict[str, Any] | None = ..., execute: bool = ...) -> dict[str, Any]:
        """
        Run Mean-CVaR optimization using the QPO blueprint.

        Args:
            returns: DataFrame of asset returns (columns = assets).
            target_return: Desired target return.
            max_weight: Per-asset weight cap.
            risk_aversion: CVaR penalty inside objective.
            api: Solver choice ("cvxpy" or "cuopt").
            solver_settings: Optional solver overrides.
            execute: If False, performs environment validation only.

        Returns:
            Dict containing weights, metrics, and raw results when execute=True.

        Raises:
            QPOEnvironmentError when dependencies are missing or QPO is absent.
        """
        ...
    


