"""
Cortex output types and data structures.

All Cortex outputs are advisory and must be validated before use.
"""

from dataclasses import dataclass, field
from datetime import datetime
from enum import Enum
from typing import Any


class OutputType(Enum):
    """Type of Cortex output."""

    RESEARCH = "research"  # Research findings and synthesis
    HYPOTHESIS = "hypothesis"  # Trading hypothesis
    STRATEGY_SPEC = "strategy_spec"  # Strategy specification
    PARAM_PROPOSAL = "param_proposal"  # Parameter recommendations
    REVIEW = "review"  # Review of engine outputs
    CODE_ANALYSIS = "code_analysis"  # Code analysis and suggestions
    MARKET_INSIGHT = "market_insight"  # Market condition analysis


@dataclass
class CortexOutput:
    """
    Standard output format from Cortex engine.

    All outputs are advisory - they propose actions but don't execute them.
    Must pass through validation (ProofBench) before implementation.
    """

    output_type: OutputType
    content: dict[str, Any]
    confidence: float  # 0.0 to 1.0
    reasoning: str  # Audit trail of AI reasoning
    requires_validation: bool = True
    timestamp: datetime = field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = field(default_factory=dict)

    # AI model attribution
    model_used: str | None = None
    model_version: str | None = None
    prompt_tokens: int = 0
    completion_tokens: int = 0

    def __post_init__(self):
        """Validate output."""
        if not 0.0 <= self.confidence <= 1.0:
            raise ValueError(f"Confidence must be in [0, 1], got {self.confidence}")

    def to_dict(self) -> dict[str, Any]:
        """Convert output to dictionary."""
        return {
            "output_type": self.output_type.value,
            "content": self.content,
            "confidence": self.confidence,
            "reasoning": self.reasoning,
            "requires_validation": self.requires_validation,
            "timestamp": self.timestamp.isoformat(),
            "metadata": self.metadata,
            "model_used": self.model_used,
            "model_version": self.model_version,
            "prompt_tokens": self.prompt_tokens,
            "completion_tokens": self.completion_tokens,
        }


@dataclass
class StrategyHypothesis:
    """
    Trading strategy hypothesis generated by Cortex.

    Represents a testable trading idea that must be validated via ProofBench.
    """

    hypothesis_id: str
    name: str
    description: str
    rationale: str

    # Strategy parameters
    instrument_class: str  # "equity", "options", "futures", etc.
    time_horizon: str  # "intraday", "swing", "position"
    strategy_type: str  # "mean_reversion", "trend_following", etc.

    # Proposed parameters
    parameters: dict[str, Any]

    # Entry/exit conditions
    entry_conditions: list[str]
    exit_conditions: list[str]

    # Risk parameters
    max_position_size_pct: float
    stop_loss_pct: float
    take_profit_pct: float | None = None

    # Expected performance (from hypothesis)
    expected_sharpe: float | None = None
    expected_win_rate: float | None = None

    # Metadata
    confidence: float = 0.5
    requires_validation: bool = True
    created_at: datetime = field(default_factory=datetime.utcnow)
    metadata: dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> dict[str, Any]:
        """Convert hypothesis to dictionary."""
        return {
            "hypothesis_id": self.hypothesis_id,
            "name": self.name,
            "description": self.description,
            "rationale": self.rationale,
            "instrument_class": self.instrument_class,
            "time_horizon": self.time_horizon,
            "strategy_type": self.strategy_type,
            "parameters": self.parameters,
            "entry_conditions": self.entry_conditions,
            "exit_conditions": self.exit_conditions,
            "max_position_size_pct": self.max_position_size_pct,
            "stop_loss_pct": self.stop_loss_pct,
            "take_profit_pct": self.take_profit_pct,
            "expected_sharpe": self.expected_sharpe,
            "expected_win_rate": self.expected_win_rate,
            "confidence": self.confidence,
            "requires_validation": self.requires_validation,
            "created_at": self.created_at.isoformat(),
            "metadata": self.metadata,
        }
