"""
This type stub file was generated by pyright.
"""

import logging
from collections.abc import MutableMapping
from typing import Any

_trace_id_ctx = ...
class JSONFormatter(logging.Formatter):
    """Formatter that outputs JSONL for structured logging."""
    def format(self, record: logging.LogRecord) -> str:
        ...
    


class StructuredLoggerAdapter(logging.LoggerAdapter):
    """Adapter that injects trace_id and handles structured data."""
    def process(self, msg: Any, kwargs: MutableMapping[str, Any]) -> tuple[Any, MutableMapping[str, Any]]:
        ...
    


def setup_logging(log_dir: str = ..., level: str = ...) -> None:
    """Configure the root logger for Ordinis."""
    ...

def get_logger(name: str) -> StructuredLoggerAdapter:
    """Get a structured logger adapter."""
    ...

class TraceContext:
    """Context manager for setting the trace_id."""
    def __init__(self, trace_id: str | None = ...) -> None:
        ...
    
    def __enter__(self) -> str:
        ...
    
    def __exit__(self, exc_type, exc_val, exc_tb): # -> None:
        ...
    


