"""
This type stub file was generated by pyright.
"""

from dataclasses import dataclass
from enum import Enum
from typing import Any

"""
Trace Logger for Ordinis Dashboard.

Captures structured events for retroactive analysis and observability.
"""
_logger = ...
class TraceType(str, Enum):
    """Types of trace events."""
    SYSTEM = ...
    MARKET_DATA = ...
    SIGNAL = ...
    RISK_CHECK = ...
    ORDER = ...
    FILL = ...
    LLM_REQUEST = ...
    LLM_RESPONSE = ...
    RAG_RETRIEVAL = ...
    CORTEX_THOUGHT = ...
    CODE_GEN = ...


@dataclass
class TraceEvent:
    """Structured trace event."""
    trace_id: str
    timestamp: float
    type: TraceType
    component: str
    content: dict[str, Any]
    parent_id: str | None = ...
    metadata: dict[str, Any] = ...
    def to_json(self) -> str:
        """Convert to JSON string."""
        ...
    


class TraceLogger:
    """
    Centralized logger for dashboard traces.

    Writes structured JSONL logs to artifacts/traces/ for ingestion by the dashboard.
    """
    def __init__(self, log_dir: str = ...) -> None:
        """Initialize trace logger."""
        ...
    
    def log(self, trace_type: TraceType, component: str, content: dict[str, Any], trace_id: str | None = ..., parent_id: str | None = ..., metadata: dict[str, Any] | None = ...) -> str:
        """
        Log a trace event.

        Args:
            trace_type: Type of event
            component: Component name (e.g., "Cortex", "Helix")
            content: Main event data
            trace_id: Correlation ID (generated if None)
            parent_id: Parent event ID
            metadata: Additional context

        Returns:
            trace_id used for the event
        """
        ...
    
    def start_trace(self) -> str:
        """Start a new trace chain and return the ID."""
        ...
    


_trace_logger = ...
def get_trace_logger() -> TraceLogger:
    """Get global trace logger instance."""
    ...

