"""
This type stub file was generated by pyright.
"""

import pandas as pd
from dataclasses import dataclass
from datetime import datetime
from ..core.model import Model, ModelConfig
from ..core.signal import Signal

"""
ATR-Optimized RSI Model - Best performing configuration from optimization.

Key improvements over standard RSI:
1. ATR-based stops (adaptive to volatility)
2. ATR-based take profit (adaptive targets)
3. Optimized thresholds: RSI < 35 entry, RSI > 50 exit
4. Per-stock tuned parameters

Optimization Results (10-day intraday data):
- DKNG: +6.9% | 63% WR | 38 trades | PF 1.85
- AMD:  +5.8% | 57% WR | 69 trades | PF 1.58
- COIN: +12.3% | 59% WR | 75 trades | PF 1.79
- PORTFOLIO: +25.0% across 182 trades

Best Parameters Found:
- RSI oversold: 35 (more relaxed than standard 30)
- ATR stop multiplier: 1.5x (tighter than 2x)
- ATR take profit: varies by stock (1.5x - 3.0x)
"""
@dataclass
class OptimizedConfig:
    """Per-stock optimized configuration."""
    rsi_oversold: int = ...
    rsi_exit: int = ...
    atr_stop_mult: float = ...
    atr_tp_mult: float = ...
    atr_scale: float = ...
    require_volume_confirmation: bool = ...
    volume_mean_period: int = ...
    enforce_regime_gate: bool = ...
    regime_sma_period: int = ...


OPTIMIZED_CONFIGS = ...
class ATROptimizedRSIModel(Model):
    """
    RSI mean-reversion with ATR-based adaptive stops and targets.

    Entry: RSI < oversold threshold (default 35)
    Exit: RSI > exit threshold (default 50) OR hit stop/target

    Stop Loss: Entry - (ATR * stop_mult)
    Take Profit: Entry + (ATR * tp_mult)
    """
    def __init__(self, config: ModelConfig) -> None:
        """Initialize with config."""
        ...
    
    def validate(self, data: pd.DataFrame) -> tuple[bool, str]:
        """Validate input data."""
        ...
    
    async def generate(self, symbol: str, data: pd.DataFrame, timestamp: datetime) -> Signal | None:
        """
        Generate trading signal.

        Returns Signal with ATR-based stop/target in metadata.
        """
        ...
    
    def describe(self) -> dict:
        """Return model description."""
        ...
    


def backtest(df: pd.DataFrame, rsi_os: int = ..., rsi_exit: int = ..., atr_stop_mult: float = ..., atr_tp_mult: float = ..., rsi_period: int = ..., atr_period: int = ..., atr_scale: float = ..., require_volume_confirmation: bool = ..., volume_mean_period: int = ..., enforce_regime_gate: bool = ..., regime_sma_period: int = ...) -> dict:
    """
    Run a simple backtest of the ATR-optimized RSI strategy.

    Returns dict with: total_return, win_rate, total_trades, profit_factor, trades
    """
    ...

